import { CarFrontIcon, CheckCircle2Icon, ExternalLinkIcon, FileCheck2Icon, FileTextIcon, SmartphoneIcon, WalletCardsIcon } from 'lucide-react';
import { useI18n } from '../contexts/I18nContext';
import { images } from '../data/images';
import { Button } from '../components/ui/Button';
import { Card } from '../components/ui/Card';
import { Accordion } from '../components/ui/Accordion';
import { SectionTitle } from '../components/ui/SectionTitle';
import { PageHero } from '../components/marketing/PageHero';
import { RentalRequestPage } from './RentalRequest';

const copy = {
  fr: {
    eyebrow: 'UBER / CHAUFFEURS', title: 'Louez une voiture pour conduire avec Uber', subtitle: 'Des véhicules électriques, des prix à la semaine et des offres flexibles pour vous accompagner sur la route.', vehicleCta: 'Voir les véhicules', uberCta: 'Visiter l’application chauffeur Uber', offerTitle: 'Une offre pensée pour les chauffeurs Uber', offer: ['Location de voitures pour chauffeurs Uber', 'Véhicules électriques', 'Prix à la semaine', 'Offres flexibles'], processTitle: 'Votre parcours en 3 étapes', process: [{ title: 'Activez votre compte Uber', body: 'Créez ou activez votre compte chauffeur directement auprès d’Uber.' }, { title: 'Envoyez vos documents', body: 'Préparez les documents demandés afin que votre dossier puisse être finalisé.' }, { title: 'Payez le dépôt de sécurité', body: 'Une fois les étapes confirmées avec notre équipe, finalisez le dépôt de sécurité.' }], docsTitle: 'Documents demandés', docs: ['Permis de conduire', 'Capture d’écran du compte Uber actif', 'Spécimen de chèque'], carsTitle: 'Choisissez votre véhicule', carsBody: 'Consultez les véhicules disponibles. Chaque véhicule possède sa propre page avec son prix, son année, son modèle et les informations de récupération.', carsCta: 'Découvrir les véhicules', supportTitle: 'Contact et assistance', supportBody: 'Vous avez une question sur le processus d’onboarding ? Utilisez le formulaire ci-dessous : notre équipe vous recontactera.', faqTitle: 'FAQ Uber', faq: [{ q: 'Comment créer mon compte Uber ?', a: 'Créez votre compte chauffeur directement dans l’application ou sur le site officiel d’Uber. Le lien ci-dessus vous redirige vers la page officielle.' }, { q: 'Comment louer une voiture ?', a: 'Consultez les véhicules, puis envoyez votre demande. NovaVolt vous contacte dans les 24 heures pour vous guider.' }, { q: 'Quelles sont les conditions ?', a: 'Les conditions et les prochaines étapes sont confirmées avec notre équipe selon votre situation et le véhicule choisi.' }, { q: 'Comment fonctionne le dépôt ?', a: 'Le dépôt de sécurité est abordé et confirmé avec vous lors de la finalisation de votre dossier.' }, { q: 'Mon compte Uber ne fonctionne pas.', a: 'Vérifiez les informations dans votre application Uber ou contactez directement le support Uber pour les questions liées à votre compte.' }, { q: 'Qu’est-ce qu’Uber Greenlight ?', a: 'Greenlight est le réseau de ressources d’Uber pour les chauffeurs. Consultez les informations officielles d’Uber pour votre ville.' }, { q: 'Quels documents sont nécessaires ?', a: 'Préparez votre permis de conduire, une capture de votre compte Uber actif et un spécimen de chèque.' }], notice: 'NovaVolt est un service indépendant. Uber est une marque de ses propriétaires respectifs.'
  },
  en: {
    eyebrow: 'UBER / DRIVERS', title: 'Rent a car to drive with Uber', subtitle: 'Electric vehicles, weekly pricing, and flexible offers to support you on the road.', vehicleCta: 'View vehicles', uberCta: 'Visit the Uber Driver app', offerTitle: 'Built for Uber drivers', offer: ['Car rentals for Uber drivers', 'Electric vehicles', 'Weekly pricing', 'Flexible offers'], processTitle: 'Your 3-step process', process: [{ title: 'Activate your Uber account', body: 'Create or activate your driver account directly with Uber.' }, { title: 'Send your documents', body: 'Prepare the required documents so that your file can be finalized.' }, { title: 'Pay the security deposit', body: 'Once the steps are confirmed with our team, complete the security deposit.' }], docsTitle: 'Required documents', docs: ['Driver’s licence', 'Screenshot of your active Uber account', 'Void cheque'], carsTitle: 'Choose your vehicle', carsBody: 'View the available vehicles. Each vehicle has its own page with pricing, year, model, and pickup information.', carsCta: 'Explore vehicles', supportTitle: 'Contact and support', supportBody: 'Have a question about the onboarding process? Use the form below and our team will contact you.', faqTitle: 'Uber FAQ', faq: [{ q: 'How do I create my Uber account?', a: 'Create your driver account directly in the Uber app or on the official Uber website. The link above takes you to the official page.' }, { q: 'How do I rent a car?', a: 'Browse the vehicles, then send your request. NovaVolt contacts you within 24 hours to guide you.' }, { q: 'What are the conditions?', a: 'The conditions and next steps are confirmed with our team according to your situation and selected vehicle.' }, { q: 'How does the deposit work?', a: 'The security deposit is discussed and confirmed with you as your file is finalized.' }, { q: 'My Uber account is not working.', a: 'Check the information in your Uber app or contact Uber Support directly for questions related to your account.' }, { q: 'What is Uber Greenlight?', a: 'Greenlight is Uber’s network of resources for drivers. Consult official Uber information for your city.' }, { q: 'What documents are required?', a: 'Prepare your driver’s licence, a screenshot of your active Uber account, and a void cheque.' }], notice: 'NovaVolt is an independent service. Uber is a trademark of its respective owners.'
  },
};

export function Fleet() {
  const { locale } = useI18n();
  const text = copy[locale === 'fr' ? 'fr' : 'en'];
  const steps = [SmartphoneIcon, FileCheck2Icon, WalletCardsIcon];
  return <><PageHero eyebrow={text.eyebrow} title={text.title} subtitle={text.subtitle} image={{ src: images.driverHero, alt: text.title }} actions={<><Button to="/vehicules" size="lg">{text.vehicleCta}</Button><Button href="https://www.uber.com/ca/en/drive/driver-app/" variant="secondary" size="lg" iconRight={<ExternalLinkIcon className="h-4 w-4" />}>{text.uberCta}</Button></>} />
    <section className="border-y border-line bg-white px-4 py-16 sm:px-6 lg:px-8 lg:py-24"><div className="mx-auto max-w-content"><SectionTitle as="h2" variant={1} title={text.offerTitle} className="max-w-2xl" /><ul className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{text.offer.map((item, index) => <Card as="li" key={item} className="flex items-center gap-3" padding="md"><CheckCircle2Icon className="h-5 w-5 shrink-0 text-action" /><span className="text-sm font-semibold text-ink">{item}</span></Card>)}</ul></div></section>
    <section className="bg-ink px-4 py-16 text-white sm:px-6 lg:px-8 lg:py-24"><div className="mx-auto max-w-content"><SectionTitle as="h2" variant={3} tone="light" title={text.processTitle} className="max-w-2xl" /><ol className="mt-10 grid gap-5 lg:grid-cols-3">{text.process.map((item, index) => { const Icon = steps[index]; return <li key={item.title} className="rounded-card border border-white/10 bg-white/5 p-6"><span className="flex items-center justify-between"><span className="grid h-11 w-11 place-items-center rounded-xl bg-sky-300/15 text-sky-300"><Icon className="h-5 w-5" /></span><span className="font-display text-2xl font-semibold text-sky-300/75">0{index + 1}</span></span><h3 className="mt-6 font-display text-xl font-semibold">{item.title}</h3><p className="mt-3 text-sm leading-relaxed text-sky-100/75">{item.body}</p></li>; })}</ol></div></section>
    <section className="bg-soft px-4 py-16 sm:px-6 lg:px-8 lg:py-24"><div className="mx-auto grid max-w-content gap-10 lg:grid-cols-[0.9fr_1.1fr] lg:items-center"><div><SectionTitle as="h2" variant={2} title={text.docsTitle} /><ul className="mt-8 space-y-4">{text.docs.map((item) => <li key={item} className="flex items-center gap-3 text-sm font-medium text-ink"><FileTextIcon className="h-5 w-5 text-action" /><span>{item}</span></li>)}</ul></div><img src="https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=1200&q=85" alt="Rental documents" className="aspect-[4/3] w-full rounded-card object-cover shadow-card" /></div></section>
    <section className="border-y border-line bg-white px-4 py-16 sm:px-6 lg:px-8 lg:py-24"><div className="mx-auto grid max-w-content gap-10 lg:grid-cols-[1fr_0.9fr] lg:items-center"><img src={images.crossover} alt="NovaVolt electric vehicle" className="order-2 aspect-[4/3] w-full rounded-card object-cover shadow-card lg:order-1" /><div className="order-1 lg:order-2"><SectionTitle as="h2" variant={0} title={text.carsTitle} subtitle={text.carsBody} /><Button to="/vehicules" className="mt-8" size="lg" iconLeft={<CarFrontIcon className="h-4 w-4" />}>{text.carsCta}</Button></div></div></section>
    <section className="bg-soft px-4 pt-16 sm:px-6 lg:px-8 lg:pt-24"><div className="mx-auto max-w-content"><SectionTitle as="h2" variant={1} title={text.supportTitle} subtitle={text.supportBody} className="max-w-2xl" /></div></section><RentalRequestPage />
    <section className="bg-white px-4 py-16 sm:px-6 lg:px-8 lg:py-24"><div className="mx-auto grid max-w-content gap-10 lg:grid-cols-[0.8fr_1.2fr]"><SectionTitle as="h2" variant={2} title={text.faqTitle} /><Accordion defaultOpenId="uber-faq-0" items={text.faq.map((item, index) => ({ id: `uber-faq-${index}`, question: item.q, answer: item.a }))} /></div><p className="mx-auto mt-8 max-w-content text-center text-2xs text-muted">{text.notice}</p></section>
  </>;
}